---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: curdapplicationdelopyment
spec:
 replicas: 1
 selector:
   matchLabels:
     app: curdapplication
 template:
  metadata:
   name: curdapplication
   labels:
     app: curdapplication
  spec:
    containers:
    - name: curdapplication
      image: gudapativaraprasad1987/curdapplication
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: curdapplicationsvc
spec:
  type: LoadBalancer
  selector:
   app: curdapplication
  ports:
   - port: 80
     targetPort: 8080
...